## Dataset analysis: `high_schools_dimension.csv`

Purpose: high school reference with tier and ownership. Used to enrich student recruitment/high-school linkage.

In [1]:
from pathlib import Path
import pandas as pd

pd.set_option("display.max_columns", 200)
DATA_DIR = Path.cwd()
df = pd.read_csv(DATA_DIR / "high_schools_dimension.csv")
df.shape

(73, 4)

In [2]:
df.head()

                 SCHOOL_NAME DISTRICT SCHOOL_TIER            OWNERSHIP
0        King's College Budo  Kampala      Tier 1  Private/Faith-based
1               Ntare School  Kampala      Tier 1         Public/Mixed
2  St. Mary's College Kisubi  Kampala      Tier 1  Private/Faith-based
3         Gayaza High School  Kampala      Tier 1  Private/Faith-based
4     Namagunga Girls School  Kampala      Tier 1  Private/Faith-based

In [3]:
df.isna().mean().sort_values(ascending=False)

SCHOOL_NAME    0.0
DISTRICT       0.0
SCHOOL_TIER    0.0
OWNERSHIP      0.0
dtype: float64

In [4]:
key = ["SCHOOL_NAME", "DISTRICT"]
df.duplicated(key).sum(), df[key].isna().any(axis=1).sum()

(np.int64(0), np.int64(0))

In [5]:
df["SCHOOL_TIER"].value_counts(dropna=False)

SCHOOL_TIER
Tier 2    58
Tier 1    15
Name: count, dtype: int64

In [6]:
df["OWNERSHIP"].value_counts(dropna=False)

OWNERSHIP
Public/Mixed           40
Private/Faith-based    33
Name: count, dtype: int64

## Advanced analytics

Focus: coverage and consistency with `student_high_schools_all` and CGPA by school tier/ownership when joined.

In [ ]:
from analysis_utils import basic_profile, missingness_report

print(basic_profile(df))
missingness_report(df, top_n=20)

BasicProfile(rows=73, cols=4, dup_rows=0, null_cells=0)

            dtype  missing_rate  missing_count  nunique
SCHOOL_NAME   str           0.0              0       73
DISTRICT      str           0.0              0       42
SCHOOL_TIER   str           0.0              0        2
OWNERSHIP     str           0.0              0        2

In [ ]:
# Coverage vs student_high_schools_all
students = pd.read_csv(DATA_DIR / "student_high_schools_all.csv")

merged = students.merge(df, left_on=["HIGH_SCHOOL","DISTRICT"], right_on=["SCHOOL_NAME","DISTRICT"], how="left")

merged["SCHOOL_TIER"].isna().mean(), merged["OWNERSHIP"].isna().mean()

KeyError: 'SCHOOL_TIER'