## Dataset analysis: `high_schools_list.csv`

Purpose: basic list of school names by district. Useful for reference validation and joining to recruitment data.

In [1]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path.cwd()
df = pd.read_csv(DATA_DIR / "high_schools_list.csv")
df.shape

(74, 2)

In [2]:
df.head()

                 school_name district
0        King's College Budo  Kampala
1               Ntare School  Kampala
2  St. Mary's College Kisubi  Kampala
3         Gayaza High School  Kampala
4     Namagunga Girls School  Kampala

In [3]:
df.isna().mean().sort_values(ascending=False)

school_name    0.0
district       0.0
dtype: float64

In [4]:
key = ["school_name", "district"]
df.duplicated(key).sum(), df[key].isna().any(axis=1).sum()

(np.int64(0), np.int64(0))

In [5]:
df["district"].value_counts().head(20)

district
Kampala        12
Wakiso          4
Jinja           3
Mukono          2
Masaka          2
Mbarara         2
Gulu            2
Lira            2
Mbale           2
Tororo          2
Arua            2
Fort Portal     2
Hoima           2
Kabarole        2
Soroti          2
Iganga          2
Kamuli          2
Nebbi           2
Kasese          2
Pallisa         1
Name: count, dtype: int64

## Advanced analytics

Focus: reference coverage vs `student_high_schools_all` and district-level counts.

In [ ]:
from analysis_utils import basic_profile, missingness_report

print(basic_profile(df))
missingness_report(df, top_n=20)

BasicProfile(rows=74, cols=2, dup_rows=0, null_cells=0)

            dtype  missing_rate  missing_count  nunique
school_name   str           0.0              0       73
district      str           0.0              0       42

In [ ]:
# Coverage vs student_high_schools_all
students = pd.read_csv(DATA_DIR / "student_high_schools_all.csv")

merged = students.merge(df, left_on=["HIGH_SCHOOL","DISTRICT"], right_on=["school_name","district"], how="left")

merged["school_name"].isna().mean()

np.float64(0.0)